//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waFileMaintenance.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbFileMaintenanceEntities : DbContext
    {
        public dbFileMaintenanceEntities()
            : base("name=dbFileMaintenanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblGender> tblGenders { get; set; }
        public virtual DbSet<tblPersonRecord> tblPersonRecords { get; set; }
    }
}
