//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waFileMaintenance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersonRecord
    {
        public int RecordID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public bool GenderID { get; set; }
        public string ContactNumber { get; set; }
    
        public virtual tblGender tblGender { get; set; }
    }
}
